name: CI

on:
  push:
    branches: [ "master" ]
    paths:
      - '**.ts'
      - '**.js'
      - '**.sh'
      - 'Dockerfile'
env:
  IMAGE_NAME: workable-assignment-movierama
  VERSION: latest

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running lint job on ${{ runner.os }}, triggered from ${{ github.event_name }} event at ${{ github.ref }} branch." 
      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Lint code
        run: npm install
        run: npm run lint

      - run: echo "Job status -> ${{ job.status }}."
